(function(){
'use strict';
const R=window.React,C=window.SamaraFoodCore;
const displayChild=v=>Array.isArray(v)?v.map(displayChild):C.label(v);
const h=(type,props,...children)=>R.createElement(type,props,...children.map(displayChild));
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
const localNow=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const money=v=>v==null?'Not fixed':'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const btn=(text,onClick,disabled=false,primary=false)=>h('button',{type:'button',className:'btn '+(primary?'btn-primary':'btn-secondary'),onClick,disabled},text);
const field=(label,value,onChange,type='text',extra={})=>h('label',{className:'fv-field'},label,h('input',{value:value??'',type,onChange:e=>onChange(e.target.value),...extra}));
const select=(label,value,onChange,values)=>h('label',{className:'fv-field'},label,h('select',{value,onChange:e=>onChange(e.target.value)},values.map(v=>h('option',{key:typeof v==='string'?v:v.id,value:typeof v==='string'?v:v.id},typeof v==='string'?v:v.name))));
const table=(heads,rows)=>h('div',{className:'fv-table'},h('table',null,h('thead',null,h('tr',null,heads.map(x=>h('th',{key:x},x)))),h('tbody',null,rows.length?rows.map((cells,i)=>h('tr',{key:i},cells.map((x,j)=>h('td',{key:j},x)))):h('tr',null,h('td',{colSpan:heads.length},'No records for this period.')))));
const compactOrderStyle='.fv .fv-history-table{display:table!important;width:100%!important;min-width:0!important;table-layout:fixed;border-collapse:collapse}.fv .fv-history-table>thead{display:table-header-group!important}.fv .fv-history-table>tbody{display:table-row-group!important}.fv .fv-history-table>thead>tr,.fv .fv-history-table>tbody>tr{display:table-row!important}.fv .fv-history-table>thead>tr>th,.fv .fv-history-table>tbody>tr>td{display:table-cell!important;padding:10px 5px!important;border-bottom:1px solid #ecdce4;font-size:12px;white-space:normal;word-break:normal;overflow-wrap:anywhere;text-align:left}.fv .fv-history-table>tbody>tr>td:before{display:none!important}.fv-history-table .fv-history-select{cursor:pointer}.fv-history-select:hover,.fv-history-select[aria-expanded=true]{background:#fff2f8}.fv-history-table .fv-history-toggle{background:none;border:0;color:inherit;font:inherit;text-align:left;padding:0;min-height:30px;cursor:pointer}.fv-history-toggle:focus-visible{outline:2px solid #ad0054;outline-offset:2px}.fv-history-table .fv-history-expanded{background:#fffafb}.fv-history-table .fv-history-expanded h4{margin:12px 0 6px}@media(max-width:480px){.fv .fv-history-table>thead>tr>th{font-size:10px;padding:10px 3px!important}.fv .fv-history-table>tbody>tr>td{font-size:11px;padding:10px 3px!important}}';
const card=(title,...children)=>h('section',{className:'fv-card'},h('h3',null,title),...children);
const blank=()=>({date:today(),slot:'Lunch',delivery:'12:30',instructions:'',items:[{name:'Standard meal',residents:0,employees:0}]});
function Voice({value,onChange,disabled}){
 const [active,setActive]=R.useState(false),[error,setError]=R.useState(''),[lang,setLang]=R.useState('en-IN');const ref=R.useRef(null);
 R.useEffect(()=>()=>ref.current?.abort(),[]);
 function start(){if(active){ref.current?.stop();return}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API){setError('Voice dictation is not supported in this browser. Use your keyboard microphone or type.');return}const rec=new API();ref.current=rec;rec.lang=lang;rec.continuous=false;rec.interimResults=false;rec.onresult=e=>onChange((value+' '+e.results[0][0].transcript).trim());rec.onend=()=>setActive(false);rec.onerror=e=>{setError('Voice input: '+e.error+'. You can still type.');setActive(false)};try{rec.start();setActive(true);setError('')}catch(e){setError(e.message)}}
 return h('div',null,h('textarea',{value,onChange:e=>onChange(e.target.value),disabled,rows:3}),h('div',{className:'fv-row'},select('Voice language',lang,setLang,[{id:'en-IN',name:'English'},{id:'ta-IN',name:'Tamil'}]),btn(active?'Stop microphone':'🎙 Dictate',start,disabled)),h('small',null,error||'Review the dictated text before saving or sending.'));
}
window.SamaraFoodVendor=function({client,profile}){
 const [state,setState]=R.useState(null),[tab,setTab]=R.useState('Menu'),[error,setError]=R.useState(''),[busy,setBusy]=R.useState(false),[from,setFrom]=R.useState(today().slice(0,8)+'01'),[to,setTo]=R.useState(today()),[form,setForm]=R.useState(blank),[editing,setEditing]=R.useState(null),[reason,setReason]=R.useState(''),[selected,setSelected]=R.useState(''),[receipt,setReceipt]=R.useState(null),[settings,setSettings]=R.useState(null),[report,setReport]=R.useState(null),[vendor,setVendor]=R.useState(''),[rate,setRate]=R.useState({item:'Tiffin',price:'',effective:today(),reason:''}),[ledger,setLedger]=R.useState({date:today(),amount:'',reason:'',kind:'payment'}),[inspect,setInspect]=R.useState(null);
 const [statusFilter,setStatusFilter]=R.useState('All');
 const [billingSection,setBillingSection]=R.useState(''),[orderInspect,setOrderInspect]=R.useState('');
 const statementFile=R.useRef(null);
 R.useEffect(()=>()=>{if(statementFile.current?.url)URL.revokeObjectURL(statementFile.current.url)},[]);
 const [periodOpen,setPeriodOpen]=R.useState(false),[historyOpen,setHistoryOpen]=R.useState(null);
 R.useEffect(()=>{if(tab!=='Statement')return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[tab]);
 const [vendorOptions,setVendorOptions]=R.useState([]);
 const [dialog,setDialog]=R.useState(null),[dialogValue,setDialogValue]=R.useState('');
 const dialogRef=R.useRef(null),dialogResolve=R.useRef(null),returnFocus=R.useRef(null);
 function ask(message,initial=null){return new Promise(resolve=>{returnFocus.current=document.activeElement;dialogResolve.current=resolve;setDialogValue(initial===null?'':String(initial));setDialog({message,confirm:initial===null})})}
 function closeDialog(accepted){const resolve=dialogResolve.current;dialogResolve.current=null;setDialog(null);returnFocus.current?.focus?.();resolve?.(accepted?(dialog.confirm?true:dialogValue):dialog.confirm?false:null)}
 R.useEffect(()=>{if(dialog)dialogRef.current?.querySelector('input,button')?.focus()},[dialog]);
 R.useEffect(()=>()=>{dialogResolve.current?.(null)},[]);
 const lock=R.useRef(false),request=R.useRef(null),noticeRef=R.useRef(null),headingRef=R.useRef(null);
 R.useEffect(()=>{const target=error?noticeRef.current:tab==='Messages'?headingRef.current:null;if(target){target.scrollIntoView({block:'center',behavior:'auto'});target.focus({preventScroll:true})}},[error,tab]);
 R.useEffect(()=>{setReport(null)},[from,to,vendor]);
 async function read(action,p={}){const {data,error}=await client.rpc(action==='cancel'?'fv_cancel_order':'fv_rpc',action==='cancel'?{p}:{action,p});if(error)throw Error(error.code==='23505'&&String(error.message).includes('fv_order_slot')?'An order already exists for this date and meal. Please open the existing order.':error.message);if(action==='billing'){setVendorOptions(data.vendors||[]);const quantities=await read('load',{from:p.from,to:p.to});return {...data,orders:quantities.orders,events:quantities.events,from:p.from,to:p.to,vendor_id:p.vendor_id}}return data}
 async function load(range={}){try{const data=await read('load',{from:range.from||from,to:range.to||to});setState(data);setSettings(data.settings);if(!vendor)setVendor(data.settings.vendor_id);setError('')}catch(e){setError(e.message)}}
 R.useEffect(()=>{load()},[]);
 const authority=state?.authority||{},control=authority.control&&!busy,full=authority.billing,canStatement=!!authority.read,orders=state?.orders||[],events=state?.events||[],messages=state?.messages||[];
 async function transact(action,p={}){const signature=JSON.stringify([action,p]);if(!request.current||request.current.signature!==signature)request.current={signature,id:crypto.randomUUID()};const result=await read(action,{...p,request_id:request.current.id});request.current=null;return result}
 async function run(fn){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}}
 function patch(k,v){setForm(f=>({...f,[k]:v}))}
 async function save(action){const kind=action==='modify'?'modification':'order';const auto=action!=='save'&&state.settings.approved?.[kind];if(auto&&!await ask('Finalise and send this order to '+(editing?.data.vendor_name||state.settings.vendor_name)+' by WhatsApp API?'))return;await run(async()=>{if(!form.items.some(i=>Number(i.residents)>0||Number(i.employees)>0))throw Error('Enter at least one resident or employee quantity above 0.');
 if(form.items.some(i=>!i.name.trim()||['residents','employees'].some(k=>!Number.isInteger(Number(i[k]))||Number(i[k])<0)))throw Error('Enter an item name and whole, non-negative quantities for each item.');
 const out=await transact(action,{id:editing?.id,version:editing?.version,data:form,reason});setEditing(null);setForm(blank());setReason('');setTab('Orders');const range={from:form.date<from?form.date:from,to:form.date>to?form.date:to};setFrom(range.from);setTo(range.to);await load(range);if(out.message_id){setTab('Messages');setInspect(out.message_id);if(auto){const {data,error}=await invokeFood({id:out.message_id});await load(range);if(error||data?.error)throw Error('Order saved; WhatsApp needs attention: '+(data?.error||error.message));setError('Order saved and accepted by Meta.')}else setError('Order saved. Use manual WhatsApp while the template is awaiting approval.')}})}
 async function cancelOrder(o){
  const why=await ask('Reason for cancelling '+C.ref(o.id)+' ('+o.data.date+' / '+o.data.slot+'). Nothing has been sent yet.','');
  if(!why)return;
  if(why.trim().length>500){setError('Use a cancellation reason of 500 characters or fewer.');return}
  if(!await ask('Cancel the entire order and send WhatsApp to '+o.data.vendor_name+' (+'+o.data.phone+')? Revised quantities: 0 for every item. FULL CANCELLATION - Do not prepare or deliver. Reason: '+why.trim()+'. The original order stays in History. Meta acceptance does not mean the vendor has acknowledged.'))return;
  await run(async()=>{
   const out=await transact('cancel',{id:o.id,version:o.version,reason:why.trim()});
   await load();setTab('Messages');setInspect(out.message_id);
   const {data,error}=await invokeFood({id:out.message_id});await load();
   if(error||data?.error)throw Error('Cancellation pending - WhatsApp sending needs attention: '+(data?.error||error.message)+'. Review this message before retrying.');
   setError('Cancellation sent through WhatsApp API. The order is cancelled in ERP. Please check the vendor acknowledgment; delivered/read status alone is not acceptance of the cancellation.');
  });
 }
 function cancellationInfo(o){
  if(!o.data.cancellation_message_id)return null;
  const m=messages.find(x=>x.id===o.data.cancellation_message_id);
  return h('div',{className:'fv-action-notice'},h('p',null,(o.status==='Cancellation pending'?'Cancellation pending - original order remains reserved. ':'Cancelled in ERP. ')+(m?'WhatsApp: '+m.status+'. ':'')+'Vendor acknowledgment is separate.'),h('p',null,'Reason: '+(o.data.cancellation_reason||'')),btn('View cancellation message',()=>{setTab('Messages');setInspect(o.data.cancellation_message_id)},busy));
 }
 function edit(o){setEditing(o);setForm(JSON.parse(JSON.stringify(o.data)));setReason('');setTab('New order')}
 function received(o,index,key){return events.filter(e=>e.order_id===o.id&&e.kind==='receive').reduce((n,e)=>n+Number(e.data.items[index]?.[key]||0),0)}
 function openReceive(o){setSelected(o.id);setReceipt({received_at:localNow(),remarks:'',items:o.data.items.map((it,i)=>({residents:Number(it.residents)-received(o,i,'residents'),employees:Number(it.employees)-received(o,i,'employees'),rejected:0}))});setTab('Receive')}
 async function bill(){await run(async()=>{if(!from||!to||from>to)throw Error('Select a valid From–To period.');if(full){setReport(await read('billing',{from,to,vendor_id:vendor||state.settings.vendor_id}));return}const data=await read('load',{from,to});const vendors=[...new Map([{id:data.settings.vendor_id,name:data.settings.vendor_name},...(data.orders||[]).map(o=>({id:o.data.vendor_id,name:o.data.vendor_name}))].map(v=>[v.id,v])).values()];setVendorOptions(vendors);setReport({orders:data.orders||[],events:data.events||[],vendors,vendor_id:vendor||data.settings.vendor_id,from,to,entries:[],rates:[],history:[],opening:0,unpriced_before:0,quantitiesOnly:true});})}
 async function invokeFood(body){
  const {data:sessionData,error:sessionError}=await client.auth.getSession();
  if(sessionError||!sessionData?.session?.access_token)return {error:Error('Please sign in again before using WhatsApp.')};
  const result=await client.functions.invoke('food-whatsapp',{body,headers:{Authorization:'Bearer '+sessionData.session.access_token}});
  if(result.error?.context){try{const detail=await result.error.context.json();if(detail?.error||detail?.message)result.error=Error(detail.error||detail.message)}catch(_){}}
  return result;
 }
 async function send(m){if(!await ask('Send this '+(m.snapshot.cancellation?'CANCELLATION':m.kind)+' message to '+m.snapshot.vendor_name+' (+'+m.snapshot.phone+')?'))return;await run(async()=>{const {data,error}=await invokeFood({id:m.id});if(error||data?.error)throw Error(data?.error||error.message);await load();setError(m.snapshot.cancellation?'Meta accepted the cancellation message. The order is cancelled in ERP; check the vendor acknowledgment separately.':'Meta accepted the message. Delivery status updates separately.')} )}
 async function manual(m){if(['Accepted','Sent','Delivered','Read','Manual confirmed','Superseded'].includes(m.status))return;if(['Sending','Unknown'].includes(m.status)&&!await ask('The API outcome is uncertain. Check the vendor chat first. Open manual WhatsApp anyway?'))return;window.open(C.manual(m.kind,m.snapshot),'_blank','noopener,noreferrer')}
 const statementStyle=`#fv-statement{-webkit-text-size-adjust:100%;text-size-adjust:100%;font:11px Arial,sans-serif;color:#222;max-width:186mm;margin:0 auto}#fv-statement .fv-logo{display:block;width:180px!important;height:auto!important;max-height:none!important;object-fit:contain;print-color-adjust:exact;-webkit-print-color-adjust:exact}#fv-statement h2{font-size:17px;margin:6px 0}#fv-statement .fv-vendor{font-size:20px;font-weight:800;margin:8px 0}#fv-statement p{font-size:11px;margin:6px 0 12px}#fv-statement .fv-table{overflow-x:auto;-webkit-overflow-scrolling:touch;max-width:100%}#fv-statement table{display:table!important;width:100%;min-width:680px;border-collapse:collapse;table-layout:fixed;font-size:10px}#fv-statement thead{display:table-header-group!important}#fv-statement tbody{display:table-row-group!important}#fv-statement tr{display:table-row!important;break-inside:avoid}#fv-statement th,#fv-statement td{display:table-cell!important;border:1px solid #aaa;padding:6px 3px;text-align:center;overflow-wrap:normal;word-break:normal;line-height:1.35;-webkit-text-size-adjust:100%}#fv-statement td:before{display:none!important}#fv-statement th{font-weight:bold;background:#f3f3f3;color:#222}#fv-statement th:first-child{width:16%}#fv-statement th:nth-child(2){width:18%}#fv-statement tr:last-child td{font-weight:bold;background:#f5f5f5}#fv-statement small{display:block;font-size:9px;margin-top:8px}#fv-statement .fv-meal-summary{width:480px;max-width:100%;margin:16px 0 0}#fv-statement .fv-meal-summary table{min-width:0;table-layout:auto}#fv-statement .fv-meal-summary th:first-child{width:32%}#fv-statement .fv-meal-summary th:nth-child(2){width:auto}#fv-statement .fv-meal-summary th,#fv-statement .fv-meal-summary td{white-space:normal;padding:7px 5px}#fv-statement .fv-meal-summary h3{font-size:12px;margin:0 0 6px}@page{size:A4 portrait;margin:12mm}@media print{body{margin:0;padding:0}#fv-statement{max-width:none}#fv-statement table{min-width:0;font-size:9px}#fv-statement .fv-table{overflow:visible}#fv-statement .fv-meal-summary{break-inside:avoid}}`;
 function pdfModel(){const numeric=(v,i)=>v==null?'—':typeof v==='number'&&(i===6||i===8)?v.toFixed(2):C.label(v);return {vendor:report.vendors.find(v=>v.id===report.vendor_id)?.name||state.settings.vendor_name,period:report.from+' to '+report.to,heads:quantityHeads.filter((_,i)=>statementColumn(i)),rows:compactData().map(r=>r.map(numeric).filter((_,i)=>statementColumn(i))),summaryHeads:full?['Meal type','Quantity','Unit price INR','Amount INR']:['Meal type','Quantity'],summary:C.mealSummary(report).map(r=>full?r.map((v,i)=>v==null?(i===2&&r[0]==='Grand total'?'—':'Not fixed'):typeof v==='number'&&i>1?v.toFixed(2):C.label(v)):r.slice(0,2).map(C.label)),notes:[statementNote,...(full?['Order value at rates effective on each supply date. Final billing uses received quantities.','Amount in words: '+C.amountWords(C.mealSummary(report).at(-1)[3])]:[])]};}
 function getStatementFile(){
 const model=pdfModel(),key=JSON.stringify(model);if(statementFile.current?.key===key)return statementFile.current;
 const logoImage=document.querySelector('#fv-statement .fv-logo');if(!logoImage?.complete||!logoImage.naturalWidth)throw Error('The Samara logo is still loading. Please try again.');
 const file=new File([C.statementPdf({...model,logoImage})],'Samara-food-statement-'+C.dateText(report.from)+'-to-'+C.dateText(report.to)+'.pdf',{type:'application/pdf'});
 if(statementFile.current?.url)URL.revokeObjectURL(statementFile.current.url);statementFile.current={key,file,url:URL.createObjectURL(file)};return statementFile.current;
 }
 async function whatsappPdf(){if(!report)return;try{const {file,url}=getStatementFile();if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'Samara Food Vendor Statement'});return}const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setError('The same Print / Save PDF file has been downloaded. Attach it as a document in WhatsApp.');}catch(e){if(e.name!=='AbortError')setError('Could not share PDF: '+e.message)}}
 function printReport(){if(!report)return;try{const {url}=getStatementFile();const w=window.open(url,'_blank');if(!w){setError('Allow the PDF window to open.');return}setError('Use the PDF viewer’s Print or Save control. Send WhatsApp shares this exact PDF.');}catch(e){setError('Could not open PDF: '+e.message)}}
 if(!state)return card('Food Vendor Management',h('p',{role:'status'},error||'Loading secure vendor workspace…'),btn('Retry',load));
 const nav=['Orders','Receive','History','Messages',...(canStatement?['Statement']:[]),...(full?['Billing','Settings']:[])];
 function orderPage(){return h(R.Fragment,null,card(editing?(editing.status==='Draft'?'Edit draft':'Modify order'):'New vendor order',h('div',{className:'fv-grid'},field('Date',form.date,v=>patch('date',v),'date',{disabled:!!editing&&editing.status!=='Draft'}),select('Meal slot',form.slot,v=>patch('slot',v),C.slots),field('Expected delivery (India time)',form.delivery,v=>patch('delivery',v),'time')),table(['Item','Residents','Employees',''],form.items.map((it,i)=>[field('Item',it.name,v=>patch('items',form.items.map((x,j)=>i===j?{...x,name:v}:x))),...['residents','employees'].map(k=>field(k,it[k],v=>patch('items',form.items.map((x,j)=>i===j?{...x,[k]:Number(v)}:x)),'number',{min:0,step:1})),btn('Remove',()=>patch('items',form.items.filter((_,j)=>j!==i)),!control||form.items.length===1)])),btn('Add item',()=>patch('items',[...form.items,{name:'',residents:0,employees:0}]),!control||form.items.length>=20),h('h4',null,'Requests / instructions'),h(Voice,{value:form.instructions,onChange:v=>patch('instructions',v),disabled:!control}),editing&&editing.status!=='Draft'?field('Modification reason',reason,setReason):null,h('p',null,'Total: '+form.items.reduce((n,i)=>n+Number(i.residents||0)+Number(i.employees||0),0)+' portions. '+(editing?'Vendor remains '+editing.data.vendor_name:'Vendor: '+state.settings.vendor_name)),h('div',{className:'fv-row'},editing&&editing.status!=='Draft'?btn(state.settings.approved?.modification?'Save modification & send WhatsApp':'Save modification & prepare message',()=>save('modify'),!control,true):h(R.Fragment,null,btn(busy?'Saving…':'Save draft',()=>save('save'),!control),btn(busy?'Preparing message…':state.settings.approved?.order?'Finalise & send WhatsApp':'Finalise & prepare message',()=>save('finalise'),!control,true)),error?h('p',{className:'fv-action-notice'},error):null,btn('Cancel form',()=>{setEditing(null);setForm(blank());setReason('');setError('');request.current=null;setTab('Orders')},busy))))}
 function orderList(){const list=orders.filter(o=>C.matchesOrderFilter(o,events,statusFilter)).sort((a,b)=>b.data.date.localeCompare(a.data.date)||C.slots.indexOf(a.data.slot)-C.slots.indexOf(b.data.slot));return card('Orders in selected period',h('style',null,compactOrderStyle),h('p',null,'Tap any row to see its details and available actions.'),h('table',{className:'fv-history-table'},h('colgroup',null,[36,19,19,26].map((width,i)=>h('col',{key:i,style:{width:width+'%'}}))),h('thead',null,h('tr',null,['Date / Meal','Ordered','Received','Status'].map(x=>h('th',{key:x,scope:'col'},x)))),h('tbody',null,list.length?list.map(o=>{const progress=C.orderProgress(o,events),open=orderInspect===o.id,toggle=()=>setOrderInspect(open?'':o.id),receipts=events.filter(e=>e.order_id===o.id&&e.kind==='receive');return h(R.Fragment,{key:o.id},h('tr',{className:'fv-history-select',onClick:e=>{e.stopPropagation();toggle()},'aria-expanded':open},h('td',null,h('button',{type:'button',className:'fv-history-toggle','aria-expanded':open,'aria-controls':'fv-order-'+o.id,onClick:e=>{e.stopPropagation();toggle()}},o.data.date+' / '+o.data.slot)),h('td',null,progress.ordered),h('td',null,progress.received??'—'),h('td',null,h('strong',null,progress.status),(()=>{const facts=C.orderFilterFacts(o,events);return facts.rejected||facts.shortage?h('small',{style:{display:'block'}},[facts.rejected?'Rejected: '+facts.rejected:'',facts.shortage?'Shortage: '+facts.shortage:''].filter(Boolean).join(' · ')):null})())),open?h('tr',{className:'fv-history-expanded',id:'fv-order-'+o.id},h('td',{colSpan:4},h('h4',null,'Order '+C.ref(o.id)),historyDetails({order_id:o.id,data:{after:o.data}}),cancellationInfo(o),receipts.length?h('div',null,h('h4',null,'Delivery receipts'),receipts.map(e=>h('section',{key:e.id||e.created_at},historyDetails(e)))):null,h('div',{className:'fv-row'},['Draft','Ordered'].includes(o.status)?btn(o.status==='Draft'?'Edit':'Modify',()=>edit(o),!control||busy):null,['Ordered','Partial'].includes(o.status)?btn('Receive',()=>openReceive(o),!control||busy):null,o.status==='Ordered'&&!receipts.length?btn('Cancel order & send WhatsApp',()=>cancelOrder(o),!control||!state.settings.approved?.modification):null,['Ordered','Partial'].includes(o.status)?btn('Close balance',async()=>{const why=await ask('Reason for closing the outstanding balance (not billed):','');if(why)run(async()=>{await transact('close',{id:o.id,version:o.version,reason:why});await load()})},!control||busy):null,btn('Close details',toggle)))):null)}):h('tr',null,h('td',{colSpan:4},'No records for this period.')))));}

 function receivePage(){const o=orders.find(x=>x.id===selected);return h(R.Fragment,null,card('Receive a delivery',select('Open order',selected,id=>{const chosen=orders.find(x=>x.id===id);if(chosen)openReceive(chosen)},[{id:'',name:'Select order'},...orders.filter(o=>['Ordered','Partial'].includes(o.status)).map(o=>({id:o.id,name:o.data.date+' · '+o.data.slot+' · '+C.ref(o.id)}))]),o&&receipt?h(R.Fragment,null,field('Actual receipt time',receipt.received_at,v=>setReceipt({...receipt,received_at:v}),'datetime-local'),table(['Item','Remaining R / E','Accept residents','Accept employees','Rejected'],o.data.items.map((it,i)=>[it.name,`${it.residents-received(o,i,'residents')} / ${it.employees-received(o,i,'employees')}`,...['residents','employees','rejected'].map(k=>field(k,receipt.items[i][k],v=>setReceipt({...receipt,items:receipt.items.map((x,j)=>i===j?{...x,[k]:Number(v)}:x)}),'number',{min:0,step:1}))])),h('h4',null,'Receipt remarks / instructions'),h(Voice,{value:receipt.remarks,onChange:v=>setReceipt({...receipt,remarks:v}),disabled:!control}),btn(state.settings.approved?.receipt?'Confirm receipt & send WhatsApp':'Confirm receipt & prepare message',()=>run(async()=>{const out=await transact('receive',{id:o.id,version:o.version,data:{...receipt,received_at:new Date(receipt.received_at).toISOString()}});setReceipt(null);setSelected('');await load();setTab('Messages');setInspect(out.message_id);if(state.settings.approved?.receipt){const {data,error}=await invokeFood({id:out.message_id});await load();if(error||data?.error)throw Error('Receipt saved; WhatsApp needs attention: '+(data?.error||error.message));setError('Receipt saved and accepted by Meta.')}}),!control,true),btn('Cancel form',()=>{setReceipt(null);setSelected('');setError('');request.current=null},busy),h('p',null,'Accepted quantities are billed. Rejected quantities remain outstanding until replaced or closed with a reason.')):null))}
 function messagePage(){return h(R.Fragment,null,messages.length?messages.map(m=>{const info=C.message(m.kind,m.snapshot),done=['Accepted','Sent','Delivered','Read','Manual confirmed','Superseded'].includes(m.status);return card(C.ref(m.order_id)+' · '+(m.snapshot.cancellation?'CANCELLATION':m.kind),h('div',{className:'fv-row'},h('strong',null,m.status),h('span',null,'To: '+m.snapshot.vendor_name+' / +'+m.snapshot.phone)),h('details',{open:inspect===m.id},h('summary',null,'Review message'),h('img',{src:C.logo,alt:'Samara logo',className:'fv-logo'}),h('pre',null,info.text)),m.error?h('p',{role:'status'},m.error):null,h('div',{className:'fv-row'},btn('Send via WhatsApp API',()=>send(m),!control||!['Pending','Failed'].includes(m.status)||!state.settings.approved?.[m.kind],true),btn('Open manual WhatsApp',()=>manual(m),!control||done),btn('Confirm manually sent',async()=>{const note=await ask('Only confirm after pressing Send in WhatsApp. Enter a note/reference:','');if(note)run(async()=>{await transact('manual',{id:m.id,reason:note});await load()})},!control||done),full&&['Unknown','Sending'].includes(m.status)?btn('Authorise retry after checking',async()=>{const note=await ask('Confirm this message was NOT delivered. Record how you checked:','');if(note)run(async()=>{await transact('release',{id:m.id,reason:note});await load()})},busy):null),h('small',null,'API uses a logo image header. Manual uses a Samara website link for its logo preview; WhatsApp controls preview display. Manual confirmation is not a delivery receipt.'))}):card('Messages',h('p',null,'Finalise an order or receipt to prepare its message.')))}
 function settingsPage(){return card('Vendor & WhatsApp settings',h('div',{className:'fv-grid'},field('Vendor name',settings.vendor_name,v=>setSettings({...settings,vendor_name:v})),field('International WhatsApp number',settings.phone,v=>setSettings({...settings,phone:v.replace(/\D/g,'')}),'tel')),h('p',null,'Changing vendor name or number creates a new vendor identity for future orders. Existing orders and billing retain their original identity.'),h('h4',null,'Agreed cutoff · minutes before original delivery time'),h('div',{className:'fv-grid'},C.slots.map(slot=>field(slot,settings.cutoffs?.[slot]??'',v=>setSettings({...settings,cutoffs:{...settings.cutoffs,[slot]:v===''?null:Number(v)}}),'number',{min:0,max:10080}))),btn('Check WhatsApp server connection',()=>run(async()=>{const {data,error}=await invokeFood({action:'check'});if(error||data?.error)throw Error(data?.error||error.message);setError(data.message)}),busy),h('h4',null,'Confirm Meta template approval'),['order','modification','receipt'].map(kind=>h('label',{className:'fv-row',key:kind},h('input',{type:'checkbox',checked:!!settings.approved?.[kind],onChange:e=>setSettings({...settings,approved:{...settings.approved,[kind]:e.target.checked}})}),'samara_food_'+kind+' · English · Samara image header approved')),btn('Save settings',()=>run(async()=>{await transact('settings',{data:settings});await load()}),busy,true),h('p',null,'Primary: Nursing Manager. STD inherits the active Stores assignment. Admin/Director always retain full control.'))}
 function historyDetails(e){
 const d=e.data||{},o=orders.find(x=>x.id===e.order_id),snapshot=d.after||o?.data||{};
 const info=(label,value)=>value!==undefined&&value!==null&&value!==''?h('p',null,h('strong',null,label+': '),String(value)):null;
 const quantities=(data,title,receipt=false)=>data?.items?h('div',null,h('h4',null,title),table(receipt?['Meal / item','Accepted residents','Accepted employees','Rejected']:['Meal / item','Residents','Employees','Total'],data.items.map((it,i)=>[it.name||snapshot.items?.[i]?.name||'Meal',it.residents??0,it.employees??0,receipt?it.rejected??0:Number(it.residents||0)+Number(it.employees||0)]))):null;
 return h('div',{className:'fv-history-detail'},info('Supply date',snapshot.date),info('Meal',snapshot.slot),info('Vendor',snapshot.vendor_name),info('Delivery time',snapshot.delivery),quantities(d.after,'Ordered quantities'),e.kind==='receive'?quantities(d,'Received quantities',true):null,d.before?.items?h('details',null,h('summary',null,'Previous quantities'),quantities(d.before,'Before this change'),info('Previous instructions',d.before.instructions)):null,info('Instructions',snapshot.instructions),info('Received on',d.received_at?new Date(d.received_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):''),info('Remarks',d.remarks),info('Reason',d.reason||d.note),info('Meal category',d.item),info('Effective date',d.effective),info('Price',d.price!=null?money(d.price):null),info('Amount',d.amount!=null?money(d.amount):null));
 }
 function historyPage(){
 const action=e=>({finalise:'Order finalised',save:'Draft saved',modify:'Order modified',receive:'Delivery received',close:'Order closed',cancel:'Cancellation requested',cancel_sent:'Cancellation notification sent'})[e.kind]||e.kind;
 const list=orders.filter(o=>C.matchesOrderFilter(o,events,statusFilter)).sort((a,b)=>b.data.date.localeCompare(a.data.date)||C.slots.indexOf(a.data.slot)-C.slots.indexOf(b.data.slot));

 return card('Order history',h('style',null,compactOrderStyle),h('p',null,'Tap any row to see its order and delivery details.'),canStatement?btn('Statement for selected period',async()=>{setPeriodOpen(false);setTab('Statement');await bill()},busy,true):null,h('table',{className:'fv-history-table'},h('colgroup',null,[36,19,19,26].map((width,i)=>h('col',{key:i,style:{width:width+'%'}}))),h('thead',null,h('tr',null,['Date / Meal','Ordered','Received','Status'].map(x=>h('th',{key:x,scope:'col'},x)))),h('tbody',null,list.length?list.map(o=>{
 const progress=C.orderProgress(o,events),open=historyOpen===o.id,toggle=()=>setHistoryOpen(open?null:o.id),timeline=events.filter(e=>e.order_id===o.id).sort((a,b)=>a.created_at.localeCompare(b.created_at));
 return h(R.Fragment,{key:o.id},h('tr',{className:'fv-history-select',onClick:e=>{e.stopPropagation();toggle()},'aria-expanded':open},h('td',null,h('button',{type:'button',className:'fv-history-toggle','aria-expanded':open,'aria-controls':'fv-history-'+o.id,onClick:e=>{e.stopPropagation();toggle()}},o.data.date+' / '+o.data.slot)),h('td',null,progress.ordered),h('td',null,progress.received??'—'),h('td',null,h('strong',null,progress.status),(()=>{const facts=C.orderFilterFacts(o,events);return facts.rejected||facts.shortage?h('small',{style:{display:'block'}},[facts.rejected?'Rejected: '+facts.rejected:'',facts.shortage?'Shortage: '+facts.shortage:''].filter(Boolean).join(' · ')):null})())),open?h('tr',{className:'fv-history-expanded',id:'fv-history-'+o.id},h('td',{colSpan:4},h('h4',null,'Order '+C.ref(o.id)),historyDetails({order_id:o.id,data:{after:o.data}}),h('h4',null,'Delivery and order history'),timeline.map(e=>h('section',{key:e.id||e.created_at+e.kind},h('h4',null,new Date(e.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' · '+action(e)),historyDetails(e))),btn('Close details',toggle))):null);
 }):h('tr',null,h('td',{colSpan:4},'No records for this period.')))));
 }
 async function excelReport(){if(!report)return;const sums=C.balance(report),name=report.vendors.find(v=>v.id===vendor)?.name||state.settings.vendor_name;
 const rows=[['SAMARA ASSISTED LIVING'],['Food Vendor Statement'],['Vendor',name],['Period',from,to],['Currency','INR'],['Note','Prices not fixed / receipts not recorded are excluded; this is not the final amount payable.'],['Opening balance',sums.opening],...(sums.unpriced?[['PROVISIONAL',sums.unpriced+' unpriced receipts; excluded from balance']]:[]),['Date','Type','Item / reason','Meal','Residents','Employees','Quantity','Unit price INR','Amount INR'],...report.entries.map(e=>[e.day,e.kind,e.data.item||e.data.reason||'',e.data.slot||'',e.data.residents??'',e.data.employees??'',e.data.quantity??'',e.kind==='Receipt'?(e.data.unit_price??'Not fixed'):'',e.amount??'Not fixed']),['Closing balance',sums.closing]];
 const blob=C.workbook([{name:'Food Statement',rows:[['SAMARA ASSISTED LIVING'],['Food Vendor Statement'],['Vendor',name],['Period',C.dateText(report.from),C.dateText(report.to)],[],quantityHeads.filter((_,i)=>statementColumn(i)),...compactData().map((r,n,all)=>r.map((v,i)=>i===0&&n>0&&all[n-1][0]===v?'':C.label(v)??'—').filter((_,i)=>statementColumn(i))),[statementNote],[],['Meal summary - ordered portions'],full?['Meal type','Quantity','Unit price INR','Amount INR']:['Meal type','Quantity'],...C.mealSummary(report).map(r=>full?r.map((v,i)=>C.label(v)??(i===2&&r[0]==='Grand total'?'':'Not fixed')):r.slice(0,2).map(C.label)),...(full?[['Amount in words',C.amountWords(C.mealSummary(report).at(-1)[3])],['Order value at rates effective on each supply date. Final billing uses received quantities.']]:[])]}]);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Samara-food-statement-'+from+'-to-'+to+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);
 }
 const statementColumn=i=>full||i<6;
 const statementNote=full?'— = not recorded / rate not fixed. Quantity = receipt quantity. Amounts in INR.':'— = received quantity not recorded.';
 const quantityHeads=['Date','Meal type','Resident','Employee','Ordered','Received','Rate ₹','Quantity','Total ₹'];
 function compactData(){const rows=C.compactRows(report),sum=i=>rows.reduce((n,r)=>n+(typeof r[i]==='number'?r[i]:0),0),all=i=>rows.length&&rows.every(r=>r[i]!=null);return [...rows,['Total','',sum(2),sum(3),sum(4),all(5)?sum(5):null,null,all(7)?sum(7):null,all(8)?Math.round(sum(8)*100)/100:null]];}
 function quantityStatement(){const rows=compactData(),display=(v,i)=>v==null?'—':(i===6||i===8)&&typeof v==='number'?v.toFixed(2):i===0&&/^\d{4}-/.test(v)?v.split('-').reverse().join('-'):v;
 return h(R.Fragment,null,h('div',{className:'fv-table'},h('table',null,h('thead',null,h('tr',null,quantityHeads.filter((_,i)=>statementColumn(i)).map(x=>h('th',{key:x},x)))),h('tbody',null,rows.map((r,n)=>h('tr',{key:n},r.map((v,i)=>{if(!statementColumn(i))return null;if(i===0){if(n>0&&rows[n-1][0]===v)return null;let span=1;while(n+span<rows.length&&rows[n+span][0]===v)span++;return h('td',{key:i,rowSpan:span,style:{verticalAlign:'middle'}},display(v,i))}return h('td',{key:i},display(v,i))})))))),h('small',null,statementNote));}
 function mealTotals(){const rows=C.mealSummary(report);return h('div',{className:'fv-meal-summary'},h('h3',null,'Meal summary · ordered portions'),table(full?['Meal type','Quantity','Unit price ₹','Amount ₹']:['Meal type','Quantity'],rows.map(r=>full?r.map((v,i)=>i<2?v:v==null?(i===2&&r[0]==='Grand total'?'—':'Not fixed'):typeof v==='number'?v.toFixed(2):v):r.slice(0,2))),full?h('small',null,'Order value at rates effective on each supply date. Final billing uses received quantities.'):null);}
 function statementContent(){return h('div',{id:'fv-statement'},h('style',null,statementStyle),h('img',{className:'fv-logo',src:C.statementLogo,alt:'Samara'}),h('h2',null,'Food Vendor Statement'),h('div',{className:'fv-vendor'},report.vendors.find(v=>v.id===report.vendor_id)?.name||state.settings.vendor_name),h('p',null,report.from+' to '+report.to),quantityStatement(),mealTotals(),full?h('p',{className:'fv-amount-words'},h('strong',null,'Amount in words: '),C.amountWords(C.mealSummary(report).at(-1)[3])):null);}
 function statementPage(){return ReactDOM.createPortal(h('div',{className:'fv fv-statement-view',role:'dialog','aria-modal':true,'aria-label':'Food vendor statement',style:{position:'fixed',inset:0,zIndex:2147483000,margin:0,background:'#fff',overflowY:'auto',overflowX:'hidden',WebkitOverflowScrolling:'touch',padding:'max(12px, env(safe-area-inset-top)) max(12px, env(safe-area-inset-right)) max(16px, env(safe-area-inset-bottom)) max(12px, env(safe-area-inset-left))'}},h('div',{className:'fv-row',style:{background:'#fff',padding:'10px 0'}},h('button',{type:'button','aria-label':'Close statement',onClick:()=>setTab('Menu'),className:'btn btn-secondary'},'←'),btn('Period',()=>setPeriodOpen(!periodOpen),busy),btn('Print / Save PDF',printReport,busy||!report,true),btn('Export Excel',excelReport,busy||!report),btn('Send WhatsApp (PDF)',whatsappPdf,busy||!report)),periodOpen?h('div',{className:'fv-row',style:{padding:'12px 0'}},field('From',from,v=>{setFrom(v);setReport(null)},'date',{disabled:busy}),field('To',to,v=>{setTo(v);setReport(null)},'date',{disabled:busy}),select('Vendor',vendor,v=>{setVendor(v);setReport(null)},vendorOptions.length?vendorOptions:[{id:state.settings.vendor_id,name:state.settings.vendor_name}]),btn('Apply period',async()=>{await bill();if(from&&to&&from<=to)setPeriodOpen(false)},busy,true)):null,error?h('p',{role:'status'},error):null,report?statementContent():h('p',{role:'status'},busy?'Loading statement…':'Choose a period to load the statement.')),document.body);}
 function billingPage(){if(!billingSection)return card('Billing',h('div',{className:'fv-row'},['Rates','Receipt prices','Payments'].map(name=>btn(name,()=>{setBillingSection(name);if(!report)bill()},busy))));return h(R.Fragment,null,h('div',{className:'fv-row'},btn('← Billing',()=>setBillingSection(''),busy),select('Vendor',vendor,v=>{setVendor(v);setReport(null)},vendorOptions.length?vendorOptions:[{id:state.settings.vendor_id,name:state.settings.vendor_name}]),!report?btn('Load vendor',bill,busy):null),billingSection==='Rates'?card('Effective-dated prices',h('p',null,'Coffee/Tea applies to both morning and evening orders. Rates apply per accepted portion. Existing receipt amounts remain unchanged.'),h('div',{className:'fv-grid'},select('Meal category',rate.item,v=>setRate({...rate,item:v}),['Tiffin','Lunch','Dinner','Coffee/Tea']),field('Unit price ₹',rate.price,v=>setRate({...rate,price:v}),'number',{min:0,step:'.01'}),field('Effective date',rate.effective,v=>setRate({...rate,effective:v}),'date'),field('Reason for rate',rate.reason,v=>setRate({...rate,reason:v}))),btn('Save new rate',()=>run(async()=>{await transact('rate',{data:{...rate,vendor_id:vendor}});setReport(await read('billing',{from,to,vendor_id:vendor}));setError('Rate saved. Existing receipts retain their original price.')}),busy),report?table(['Meal category','Effective','Price','Recorded'],report.rates.map(x=>[x.item,x.effective,money(x.price),new Date(x.created_at).toLocaleString()])):null):billingSection==='Receipt prices'?(report?card('Price existing receipt charges',table(['Date','Item','Current price','Action'],report.entries.filter(e=>e.kind==='Receipt').map(e=>[e.day,e.data.item,money(e.data.unit_price),btn('Set / correct price',async()=>{const value=await ask('Unit price for this receipt:',e.data.unit_price??'');if(value===null)return;const why=await ask('Reason for the price correction:','');if(why)run(async()=>{await transact('price',{data:{id:e.id,price:value,reason:why}});setReport(await read('billing',{from,to,vendor_id:vendor}))})},busy)]))):null):card('Payments and adjustments',h('div',{className:'fv-grid'},select('Type',ledger.kind,v=>setLedger({...ledger,kind:v}),[{id:'payment',name:'Payment (reduces balance)'},{id:'adjustment',name:'Adjustment (+ charge / − credit)'}]),field('Date',ledger.date,v=>setLedger({...ledger,date:v}),'date'),field('Amount ₹',ledger.amount,v=>setLedger({...ledger,amount:v}),'number',{step:'.01'}),field('Reference / reason',ledger.reason,v=>setLedger({...ledger,reason:v}))),btn('Record entry',()=>run(async()=>{await transact(ledger.kind,{data:{...ledger,vendor_id:vendor}});setLedger({...ledger,amount:'',reason:''});setReport(await read('billing',{from,to,vendor_id:vendor}))}),busy),report?table(['Time','Action','Details'],report.history.map(e=>[new Date(e.created_at).toLocaleString(),e.kind,JSON.stringify(e.data)])):null))}
 if(tab==='Statement'&&canStatement)return statementPage();
 return h('div',{className:'fv'},dialog?ReactDOM.createPortal(h('div',{className:'fv-dialog-backdrop'},h('div',{className:'fv-dialog',role:'dialog','aria-modal':true,'aria-labelledby':'fv-dialog-title',ref:dialogRef,onKeyDown:e=>{if(e.key==='Escape'){e.preventDefault();closeDialog(false)}if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll('input,button')],first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}},h('h3',{id:'fv-dialog-title'},dialog.confirm?'Please confirm':'Enter details'),h('p',null,dialog.message),h('form',{onSubmit:e=>{e.preventDefault();closeDialog(true)}},!dialog.confirm?h('label',null,'Value',h('input',{value:dialogValue,onChange:e=>setDialogValue(e.target.value),required:true})):null,h('div',{className:'fv-row'},h('button',{type:'submit',className:'btn btn-primary'},dialog.confirm?'Continue':'Save'),btn('Cancel',()=>closeDialog(false)))))),document.body):null,h('div',{className:'fv-row'},tab!=='Menu'?btn('← Food Vendor Management',()=>{setTab('Menu');setPeriodOpen(false);setBillingSection('')},busy):null,h('h2',{ref:headingRef,tabIndex:-1},tab==='Menu'?'Food Vendor Management':tab),tab==='Menu'?btn(busy?'Refreshing…':'Refresh',()=>run(async()=>{setReport(null);await load()}),busy):null),error?h('p',{role:'status',className:'fv-notice',ref:noticeRef,tabIndex:-1},error):null,tab==='Menu'?h('nav',{className:'fv-grid'},nav.map(n=>btn(n,async()=>{setTab(n);setPeriodOpen(false);setBillingSection('');if(n==='Statement')await bill()},busy))):null,['Orders','Receive','History','Messages'].includes(tab)||tab==='Billing'&&billingSection==='Receipt prices'?h(R.Fragment,null,btn('Period',()=>setPeriodOpen(!periodOpen),busy),periodOpen?h('div',{className:'fv-row'},field('From',from,v=>{setFrom(v);setReport(null)},'date',{disabled:busy}),field('To',to,v=>{setTo(v);setReport(null)},'date',{disabled:busy}),btn('Apply period',async()=>{if(!from||!to||from>to){setError('Select a valid From–To period.');return}await load();if(tab==='Billing')await bill();setPeriodOpen(false)},busy,true)):null):null,['Orders','History'].includes(tab)?h('div',{className:'fv-row'},select('Order status',statusFilter,value=>{setStatusFilter(value);setOrderInspect('');setHistoryOpen(null)},['All','Ordered','Received','Partially received','Rejected','Shortage','Draft','Cancellation pending','Cancelled','Closed']),h('small',null,'Rejected: includes rejected delivery quantities. Shortage: still missing after a recorded delivery. Filters can overlap.')):null,tab==='Orders'?h(R.Fragment,null,btn('New order',()=>{setEditing(null);setForm(blank());setReason('');setTab('New order')},!control,true),orderList()):tab==='New order'?orderPage():tab==='Receive'?receivePage():tab==='Messages'?messagePage():tab==='Settings'&&full?settingsPage():tab==='Billing'&&full?billingPage():tab==='History'?historyPage():null);
};
})();
