-- Samara Care ERP 1.1.1 — Password Recovery & Security
-- Safe additive migration. Does not delete or replace existing ERP data.

create table if not exists public.password_security_events (
  id bigint generated by default as identity primary key,
  login_id text,
  event_type text not null,
  ip_address text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists password_security_events_login_created_idx
  on public.password_security_events (login_id, created_at desc);

alter table public.password_security_events enable row level security;

drop policy if exists password_security_events_admin_read on public.password_security_events;
create policy password_security_events_admin_read
on public.password_security_events for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where (p.id = auth.uid() or p.auth_user_id = auth.uid())
      and lower(coalesce(p.role,'')) in ('admin','manager')
      and coalesce(p.is_active,p.active,true) = true
  )
);

revoke all on public.password_security_events from anon, authenticated;
grant select on public.password_security_events to authenticated;

select
  to_regclass('public.password_security_events') is not null as password_security_events_ready,
  exists(select 1 from information_schema.columns where table_schema='public' and table_name='profiles' and column_name='employee_email') as employee_email_ready;
