-- Samara Care ERP 2.0.0 — Clinical Charges & Revenue Management
alter table public.bill_charge_requests add column if not exists service_code text;
alter table public.bill_charge_requests add column if not exists service_name text;
alter table public.bill_charge_requests add column if not exists service_datetime timestamptz;
alter table public.bill_charge_requests add column if not exists unit text default 'Service';
alter table public.bill_charge_requests add column if not exists billable boolean not null default true;
alter table public.bill_charge_requests add column if not exists hospital_name text;
alter table public.bill_charge_requests add column if not exists doctor_name text;
alter table public.bill_charge_requests add column if not exists visit_reason text;
alter table public.bill_charge_requests add column if not exists out_time timestamptz;
alter table public.bill_charge_requests add column if not exists return_time timestamptz;
alter table public.bill_charge_requests add column if not exists escort_staff text;
alter table public.bill_charge_requests add column if not exists relative_accompanied boolean not null default false;
alter table public.bill_charge_requests add column if not exists admission_required boolean not null default false;
alter table public.bill_charge_requests add column if not exists laboratory_name text;
alter table public.bill_charge_requests add column if not exists test_name text;
alter table public.bill_charge_requests add column if not exists sample_type text;
alter table public.bill_charge_requests add column if not exists sample_collected_at timestamptz;
alter table public.bill_charge_requests add column if not exists report_status text;
alter table public.bill_charge_requests add column if not exists report_received_at timestamptz;
alter table public.bill_charge_requests add column if not exists transport_type text;
alter table public.bill_charge_requests add column if not exists paid_by_samara boolean not null default false;
create table if not exists public.diagnostic_services(id uuid primary key default gen_random_uuid(),charge_request_id uuid unique references public.bill_charge_requests(id) on delete set null,patient_id uuid not null references public.patients(id),service_type text not null,test_name text not null,laboratory_name text,sample_type text,ordered_at timestamptz not null default now(),sample_collected_at timestamptz,report_status text not null default 'Ordered',report_received_at timestamptz,bill_amount numeric,paid_by_samara boolean not null default false,requested_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.hospital_visit_records(id uuid primary key default gen_random_uuid(),charge_request_id uuid references public.bill_charge_requests(id) on delete set null,patient_id uuid not null references public.patients(id),hospital_name text not null,consulting_doctor text,visit_reason text not null,out_time timestamptz,return_time timestamptz,escort_staff text,relative_accompanied boolean not null default false,admission_required boolean not null default false,amount_paid_by_samara numeric,created_by uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.diagnostic_services enable row level security;alter table public.hospital_visit_records enable row level security;
drop policy if exists diagnostics_read on public.diagnostic_services;create policy diagnostics_read on public.diagnostic_services for select to authenticated using(public.current_user_has_role(array['Admin','Manager','Nurse','Caregiver','Accounts']));
drop policy if exists diagnostics_write on public.diagnostic_services;create policy diagnostics_write on public.diagnostic_services for all to authenticated using(public.current_user_has_role(array['Admin','Manager','Nurse','Accounts'])) with check(public.current_user_has_role(array['Admin','Manager','Nurse','Accounts']));
drop policy if exists hospital_visits_read on public.hospital_visit_records;create policy hospital_visits_read on public.hospital_visit_records for select to authenticated using(public.current_user_has_role(array['Admin','Manager','Nurse','Caregiver','Accounts']));
drop policy if exists hospital_visits_write on public.hospital_visit_records;create policy hospital_visits_write on public.hospital_visit_records for all to authenticated using(public.current_user_has_role(array['Admin','Manager','Nurse','Accounts'])) with check(public.current_user_has_role(array['Admin','Manager','Nurse','Accounts']));
alter table public.physiotherapy_sessions add column if not exists billable boolean not null default false;
alter table public.physiotherapy_sessions add column if not exists billing_rate numeric;
alter table public.physiotherapy_sessions add column if not exists charge_request_id uuid references public.bill_charge_requests(id);
notify pgrst,'reload schema';
select to_regclass('public.diagnostic_services') is not null as diagnostics_ready,to_regclass('public.hospital_visit_records') is not null as hospital_visits_ready;
